name = "riot-api-proxy-server"
main = "src/worker.ts"
compatibility_date = "2023-04-04"
env = {}

[vars]
# Riot API default region
DEFAULT_REGION = "euw1"
CACHE_DURATION = 60 # seconds
# Client rate limit (requests per second)
CLIENT_RATE_LIMIT_BURST = 5 # number of requests 
CLIENT_RATE_LIMIT_INTERVAL = 10 # seconds
# Server rate limit (requests per second)
SERVER_RATE_LIMIT_BURST = 500 # number of requests
SERVER_RATE_LIMIT_INTERVAL = 10 # seconds

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "b095bb1ae59d486ab97b46c0a88f7462"
preview_id = "2e2be3a2a37e43608a404b49bbd92e20"

[build]
command = "npm run build"
