name = "riot-api-proxy-server"
main = "src/worker.ts"
compatibility_date = "2023-04-04"
env = {}

[vars]
# Riot API default region
DEFAULT_REGION = "euw1"
CACHE_DURATION = 60 # seconds
# The multiplier is used to reduce the rate limit to avoid hitting the server rate limit
CLIENT_RATE_LIMIT_MULTIPLIER = 0.5 # 0.5 = 50% of the rate limit

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "b095bb1ae59d486ab97b46c0a88f7462"
preview_id = "2e2be3a2a37e43608a404b49bbd92e20"
